language:
- node_js
node_js:
- '10'
before_install:
- chmod 600 ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_8f8831fa9ccf_key -iv $encrypted_8f8831fa9ccf_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- cd code/frontend
install:
- npm install
script:
- npm test
after_success:
- ssh ubuntu@202.120.40.8 "./script.sh"
addons:
  ssh_known_hosts:202.120.40.8
