language:
- node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_8f8831fa9ccf_key -iv $encrypted_8f8831fa9ccf_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- cd code/frontend
install:
- npm install
script:
- npm test
