language:
- node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_955874712cff_key -iv $encrypted_955874712cff_iv
  -in key_202.120.40.8_30740.pub.enc -out /usr/tmpssh/key_202.120.40.8_30740.pub -d
- cd code/frontend
install:
- npm install
script:
- npm test
