sudo: required
language: java
#addons:
#  apt:
#    packages:
#      - oracle-java11-installer
dist: xenial
jdk:
 - openjdk11 
env:
  global:
    - CODECOV_TOKEN=c44167bb-18d7-4f63-88f5-6181d3d80c4d
script:
 - "mvn cobertura:cobertura"
# - mvn spring-boot:run
before_install: 
  - chmod a+x ./mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)
