version: '2'

services:
  registry:
    image: bamdb/registry
    hostname: registry
    restart: unless-stopped
  auth:
    image: bamdb/auth-service
    hostname: auth
    restart: unless-stopped
  item:
    image: bamdb/item-service
    hostname: auth
    restart: unless-stopped
  comment:
    image: bamdb/comment-service
    hostname: comment
    restart: unless-stopped
  friend:
    image: bamdb/friend-service
    hostname: friend
    restart: unless-stopped
  image:
    image: bamdb/image-service
    hostname: image
    restart: unless-stopped
  message:
    image: bamdb/message-service
    hostname: message
    restart: unless-stopped
  gateway:
    image: bamdb/gateway
    hostname: gateway
    restart: unless-stopped
