version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.16-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      restart_policy:
        condition: on-failure
