version: '3'

services:
  config:
    image: bamdb/config-server
    #  container_name: config
    hostname: config
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
