version: '2'

services:
  auth:
    image: bamdb/auth-service
    #  container_name: auth
    hostname: auth
    restart: unless-stopped
  activity:
    image: bamdb/activity-service
    #  container_name: activity
    hostname: activity
    restart: unless-stopped
  item:
    image: bamdb/item-service
    #  container_name: item
    hostname: item
    restart: unless-stopped
  comment:
    image: bamdb/comment-service
    #  container_name: comment
    hostname: comment
    restart: unless-stopped
  friend:
    image: bamdb/friend-service
    #  container_name: friend
    hostname: friend
    restart: unless-stopped
  image:
    image: bamdb/image-service
    # container_name: image
    hostname: image
    restart: unless-stopped
  message:
    image: bamdb/message-service
    # container_name: message
    hostname: message
    restart: unless-stopped
  rating:
    image: bamdb/rating-service
    # container_name: rating
    hostname: rating
    restart: unless-stopped
  topic:
    image: bamdb/topic-service
    #  container_name: topic
    hostname: topic
    restart: unless-stopped
  gateway:
    image: bamdb/gateway
    # container_name: gateway
    hostname: gateway
    restart: unless-stopped
    ports:
      - 8000:8000
