spring:
  application:
    name: message
  data:
    mongodb:
      uri: mongodb://localhost:27017/bamdb
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
server:
  port: ${PORT:0}

security:
  oauth2:
    client:
      clientId: message-service
      clientSecret: message-service
      accessTokenUri: http://localhost:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8000/auth/user
management:
  endpoints:
    web:
      exposure:
        include: '*'
