eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 3
    registerWithEureka: false
    fetchRegistry: true
spring:
  application:
    name: gateway

server:
  port: 8000

zuul:
  routes:
    fromimage:
      path: /auth/**
      service-id: auth
      sensitiveHeaders:
    fromuser:
      path: /user/**
      service-id: user
      sensitiveHeaders:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 17000
feign:
  hystrix:
    enabled: true
