spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bamdb/SE231.git/
          search-paths: /config
  application:
    name: config
#  security:
#    user:
#      password: ${CONFIG_SERVICE_PASSWORD}
server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
