spring:
  application:
    name: search
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://202.120.40.8:30743
    sender:
      type: web
    enabled: true
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  data:
    elasticsearch:
      cluster-nodes: 202.120.40.8:30748, 47.103.123.5:9300
      repositories:
        enabled: true
      cluster-name: bamdb

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
server:
  port: ${PORT:0}
security:
  oauth2:
    client:
      clientId: search-service
      clientSecret: search-service
      accessTokenUri: http://localhost:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8000/auth/user
management:
  endpoints:
    web:
      exposure:
        include: '*'
