spring:
  cloud:
    config:
      discovery:
        service-id: config
        enabled: true
      name: search, uniconfig, rabbitmq
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://bamdb:bamdb@registry:8761/eureka/