spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/bamdb?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 610878
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mybatis:
  type-aliases-package: com.se.userservice