spring:
  application:
    name: image
  data:
    mongodb:
      uri: mongodb://localhost:27017/bamdb
server:
  port: 3232
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10

security:
  oauth2:
    client:
      clientId: image-service
      clientSecret: image-service
      accessTokenUri: http://localhost:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8000/auth/user
management:
  endpoints:
    web:
      exposure:
        include: '*'
