spring:
  application:
    name: image

eureka:
  instance:
    hostname: image

server:
  port: 8093
security:
  oauth2:
    client:
      clientId: image-service
      clientSecret: image-service
      accessTokenUri: http://gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://gateway:8000/auth/user