spring:
  application:
    name: item

eureka:
  instance:
    hostname: item

server:
  port: 8094
security:
  oauth2:
    client:
      clientId: item-service
      clientSecret: item-service
      accessTokenUri: http://gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://gateway:8000/auth/user