spring:
  application:
    name: message

eureka:
  instance:
    hostname: message

server:
  port: 8095
security:
  oauth2:
    client:
      clientId: message-service
      clientSecret: message-service
      accessTokenUri: http://gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://gateway:8000/auth/user