spring:
  application:
    name: rating
server:
  port: ${PORT:0}
security:
  oauth2:
    client:
      clientId: rating-service
      clientSecret: rating-service
      accessTokenUri: http://localhost:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8000/auth/all