spring:
  application:
<<<<<<< HEAD
    name: message
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/bamdb
  mongodb:
    uri: mongodb://202.120.40.8:30746/bamdb?connectTimeoutMS=20000&heartbeatFrequencyMS=5000&localThresholdMS=3000&maxIdleTimeMS=5000&serverSelectionTimeoutMS=15000&socketTimeoutMS=7500
    options:
      connectTimeoutMS: 20000
      heartbeatFrequencyMS: 5000
      localThresholdMS: 3000
      maxIdleTimeMS: 5000
      serverSelectionTimeoutMS: 15000
      socketTimeoutMS: 7500
=======
    name: search
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://202.120.40.8:30743
    sender:
      type: web
    enabled: true
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  data:
<<<<<<< HEAD:code/backend/search-service/src/main/resources/application-dev.yml
    elasticsearch:
      cluster-nodes: 202.120.40.8:30748, 47.103.123.5:9300
      repositories:
        enabled: true
      cluster-name: bamdb

=======
    mongodb:
      uri: mongodb://localhost:27017/bamdb
>>>>>>> master
  zipkin:
    base-url: http://202.120.40.8:30743
    sender:
      type: web
    enabled: true
    discovery-client-enabled: true

  sleuth:
    sampler:
      probability: 1
<<<<<<< HEAD
=======
>>>>>>> master:code/backend/message-service/src/main/resources/application-dev.yml
>>>>>>> master
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
server:
  port: ${PORT:0}
<<<<<<< HEAD

security:
  oauth2:
    client:
      clientId: message-service
      clientSecret: message-service
      accessTokenUri: http://202.120.40.8:30741/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://202.120.40.8:30741/auth/user
=======
security:
  oauth2:
    client:
      clientId: search-service
      clientSecret: search-service
      accessTokenUri: http://localhost:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8000/auth/user
>>>>>>> master
management:
  endpoints:
    web:
      exposure:
        include: '*'
