spring:
  application:
    name: activity
server:
  port: 8090

security:
  oauth2:
    client:
      clientId: activity-service
      clientSecret: activity-service
      accessTokenUri: http://gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://gateway:8000/auth/all