spring:
  application:
    name: comment
server:
  port: 8091
security:
  oauth2:
    client:
      clientId: comment-service
      clientSecret: comment-service
      accessTokenUri: http://localhost:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8000/auth/user