spring:
  application:
    name: friend

eureka:
  instance:
    hostname: bamdb_friend

server:
  port: 8092
security:
  oauth2:
    client:
      clientId: friend-service
      clientSecret: friend-service
      accessTokenUri: http://bamdb_gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://bamdb_gateway:8000/auth/user