spring:
  application:
    name: gateway
server:
  port: 8000
eureka:
  client:
    registry-fetch-interval-seconds: 60
    register-with-eureka: false
    fetch-registry: true
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    fromimage:
      path: /image/**
      url: forward:/
      service-id: image
      sensitiveHeaders:
    fromuser:
      path: /user/**
      url: forward:/
      service-id: user
      sensitiveHeaders:
    fromitem:
      path: /item/**
      url: forward:/
      service-id: item
      sensitiveHeaders:
    fromactivity:
      path: /activity/**
      url: forward:/
      service-id: activity
      sensitiveHeaders:
    fromrating:
      path: /rating/**
      url: forward:/
      service-id: rating
      sensitiveHeaders:
    fromtopic:
      path: /topic/**
      url: forward:/
      service-id: topic
      sensitiveHeaders:
    fromfriend:
      path: /friend/**
      url: forward:/
      service-id: friend
      sensitiveHeaders:
    frommessage:
      path: /message/**
      url: forward:/
      service-id: message
      sensitiveHeaders:
    fromcomment:
      path: /comment/**
      url: forward:/
      service-id: comment
      sensitiveHeaders:
    fromauth:
      path: /auth/**
      url: forward:/
      service-id: auth
      sensitiveHeaders:
  retryable: true
  semaphore:
    max-semaphores: 10000
  ignored-services: "*"
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
