spring:
  application:
    name: gateway
server:
  port: 8000
zuul:
  routes:
    fromimage:
      path: /image/**
      service-id: image
      sensitiveHeaders:
    fromuser:
      path: /user/**
      service-id: user
      sensitiveHeaders:
    fromitem:
      path: /item/**
      service-id: item
      sensitiveHeaders:
    fromactivity:
      path: /activity/**
      service-id: activity
      sensitiveHeaders:
    fromrating:
      path: /rating/**
      service-id: rating
      sensitiveHeaders:
    fromtopic:
      path: /topic/**
      service-id: topic
      sensitiveHeaders:
  retryable: true

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
  OktoRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000