server:
  port: 8000
spring:
  application:
    name: gateway

zuul:
  routes:
    fromimage:
      path: /image/**
      #      url: http://image:10000
      service-id: image
      sensitiveHeaders:
    fromuser:
      path: /user/**
      service-id: user
      sensitiveHeaders:
    fromitem:
      path: /item/**
      service-id: item
      sensitiveHeaders:
  retryable: true

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
  OktoRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000