spring:
  application:
    name: image

eureka:
  instance:
    hostname: bamdb_image

server:
  port: 8093
security:
  oauth2:
    client:
      clientId: image-service
      clientSecret: image-service
      accessTokenUri: http://bamdb_gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://bamdb_gateway:8000/auth/user