spring:
  application:
    name: item
server:
  port: 8090
security:
  oauth2:
    client:
      clientId: item-service
      clientSecret: item-service
      accessTokenUri: http://localhost:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8000/auth/user