spring:
  application:
    name: registry
  security:
    user:
      password: bamdb
      name: bamdb
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#    service-url:
#      defaultZone:  http://bamdb:bamdb@47.103.107.39:8761/eureka/
  server:
<<<<<<< HEAD
    eviction-interval-timer-in-ms: 30000
=======
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
>>>>>>> 129c22f014f75eb56fe4ee46e3ce1f75e39780ad
server:
  port: 8761
