spring:
  application:
    name: registry
  security:
    user:
      password: bamdb
      name: bamdb
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://bamdb:bamdb@localhost:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
server:
  port: 8761