spring:
  application:
    name: registry
  security:
    user:
      password: bamdb
      name: bamdb
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    eviction-interval-timer-in-ms: 30000
    enable-self-preservation: false
server:
  port: 8761
