spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  OktoRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000
