spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  OktoRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
        timeout:
          enabled: false
