spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  ConnectTimeout: 1500
  ReadTimeout: 4000
  OktoRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 40000
        timeout:
          enabled: true
