spring:
  application:
    name: search

eureka:
  instance:
    hostname: search

server:
  port: 8098
security:
  oauth2:
    client:
      clientId: search-service
      clientSecret: search-service
      accessTokenUri: http://gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://gateway:8000/auth/user