spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-nodes: 202.120.40.8:30748, 47.103.107.39:9300, 47.103.104.210:9300, 47.103.98.30:9300
      repositories:
        enabled: true
      cluster-name: bamdb
eureka:
  instance:
    hostname: search

server:
  port: 8098
security:
  oauth2:
    client:
      clientId: search-service
      clientSecret: search-service
      accessTokenUri: http://gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://gateway:8000/auth/user