spring:
  application:
    name: topic

eureka:
  instance:
    hostname: bamdb_topic

server:
  port: 8097
security:
  oauth2:
    client:
      clientId: topic-service
      clientSecret: topic-service
      accessTokenUri: http://bamdb_gateway:8000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://bamdb_gateway:8000/auth/user